# Generated by Django 2.1.2 on 2020-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservendor',
            name='image',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='profiles/images/'),
        ),
    ]
