# Generated by Django 2.1.2 on 2020-06-20 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='car/images/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodimage', models.ImageField(blank=True, null=True, upload_to='food/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='house/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('gps_address', models.CharField(blank=True, max_length=255, null='N/A')),
                ('contact', models.CharField(max_length=255)),
                ('time_orderd', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_pk', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('previous_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('percentage_discount', models.CharField(default=0.0, help_text="Do not add the '%' sign", max_length=255)),
                ('contact', models.PositiveIntegerField()),
                ('contact2', models.PositiveIntegerField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(choices=[('Ashanti', 'Ashanti'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('North East', 'North East'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('Volta', 'Volta'), ('Western', 'Western'), ('Western North', 'Western North')], default='Greater Accra', max_length=20)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('CLOTHING', 'CLOTHING')], default='ELECTRONICS', max_length=50)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('negotiable', models.CharField(choices=[('Negotiable', 'Negotiable'), ('Not Negotiable', 'Not Negotiable')], default='Negotiable', max_length=255)),
                ('description', models.TextField(help_text='please be precise', max_length=300)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='product/images/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('verified_id', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quick_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='example: Toyota,Benz,etc.', max_length=255)),
                ('model', models.CharField(help_text='example: corolla', max_length=255)),
                ('model_year', models.PositiveIntegerField()),
                ('millage', models.CharField(blank=True, max_length=255, null=True)),
                ('manual', models.BooleanField()),
                ('automatic', models.BooleanField()),
                ('petrol', models.BooleanField()),
                ('diesel', models.BooleanField()),
                ('hybrid', models.BooleanField()),
                ('electric', models.BooleanField()),
                ('other', models.BooleanField()),
                ('description', models.TextField(help_text='please be precise')),
                ('region', models.CharField(choices=[('Ashanti', 'Ashanti'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('North East', 'North East'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('Volta', 'Volta'), ('Western', 'Western'), ('Western North', 'Western North')], default='Greater Accra', max_length=20)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('contact', models.PositiveIntegerField()),
                ('contact2', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('negotiable', models.CharField(choices=[('Negotiable', 'Negotiable'), ('Not Negotiable', 'Not Negotiable')], default='Negotiable', max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bed', models.PositiveIntegerField(help_text='Number of beds')),
                ('bath', models.PositiveIntegerField(help_text='Number washrooms')),
                ('description', models.TextField(help_text='please be precise', max_length=50)),
                ('region', models.CharField(choices=[('Ashanti', 'Ashanti'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('North East', 'North East'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('Volta', 'Volta'), ('Western', 'Western'), ('Western North', 'Western North')], default='Greater Accra', max_length=20)),
                ('property', models.CharField(choices=[('LAND', 'LAND'), ('APARTMENT', 'APARTMENT'), ('HOUSE', 'HOUSE')], default='APARTMENT', max_length=20)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('contact', models.PositiveIntegerField()),
                ('contact2', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('negotiable', models.CharField(choices=[('Negotiable', 'Negotiable'), ('Not Negotiable', 'Not Negotiable')], default='Negotiable', max_length=255)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_pk', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CLEANING', 'CLEANING'), ('PLUMBING', 'PLUMBING'), ('ELECTRICAL', 'ELECTRICAL'), ('GARDEN', 'GARDEN'), ('TILING', 'TILING'), ('LAUNDRY', 'LAUNDRY'), ('CARPENTRY', 'CARPENTRY')], default='PLUMBING', max_length=30)),
                ('trade_name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Ashanti', 'Ashanti'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('North East', 'North East'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('Volta', 'Volta'), ('Western', 'Western'), ('Western North', 'Western North')], default='Greater Accra', max_length=20)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('service_description', models.TextField(help_text='please be precise', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='vendor/images/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.Vendor')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AddField(
            model_name='houseimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houseimages', to='ecommerce.RentHouse'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.OrderFood'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimages', to='ecommerce.RentCar'),
        ),
    ]
